// app/src/components/cards/TheoryCard.vue
<template>
    <div class="card theory-card">
        <div class="theory-card__left">
            <img class="theory-card__image" :src="imageURL" :alt="title">
        </div>
        <div class="theory-card__center">{{ title }}</div>
    </div>
</template>

<script>
import {computed} from 'vue';

export default {
    name: 'TheoryCard',
    props: {
        image: {
            type: String,
            required: true
        },
        title: {
            type: String,
            required: true
        }
    },
    setup(props) {
        const imageURL = computed(() => `/assets/img/${props.image}`);

        return {
            imageURL
        };
    }
};
</script>

<style lang="scss" scoped>
@import '@/variables';

.theory-card {
  display: grid;
  grid-template-columns: 1fr 2fr;
  color: $primary-text-color;
  cursor: pointer;

  &:hover {
    box-shadow: 0 0 2px 2px $green-accent inset;
  }

  &__center {
    margin-left: 16px;
    font-size: 18px;
    font-weight: bold;
  }
}

@media screen and (max-width: 650px) {
  .theory-card {
    max-width: 350px;
    margin: 0 auto;
  }
}

</style>

// src/app/_components/theory-card.tsx
import Image from "next/image";
interface TheoryCardProps {
  title: string;
  image: string;
}

export function TheoryCard({ title, image }: TheoryCardProps) {
  return (
    <div className="relative mb-4 grid w-0 min-w-full cursor-pointer grid-cols-[1fr_2fr] items-center overflow-hidden rounded-[16px] bg-surface p-4 text-ink-2 shadow-[2px_3px_10px_rgba(0,0,0,0.2)] transition-shadow hover:shadow-[inset_0_0_2px_2px_#3eaf7c] max-[650px]:mx-auto max-[650px]:max-w-[350px]">
      <div>
        <Image
          className="block h-auto max-w-full"
          src={`/card-icons/${image}`}
          alt={title}
          width={80}
          height={80}
        />
      </div>
      <div className="ml-4 text-[18px] font-bold leading-[24px]">{title}</div>
    </div>
  );
}
