// app/src/components/cards/TrainingCard.vue
<template>
    <div class="card training-card">
        <div class="training-card__left">
            <img class="training-card__image" :src="imageURL" :alt="title">
        </div>
        <div class="training-card__center">{{ title }}</div>
<!--        <div class="training-card__progress" v-if="progress">{{ progressPercent }}</div>-->
    </div>
</template>

<script>
import {computed} from 'vue';

export default {
    name: 'TrainingCard',
    props: {
        image: {
            type: String,
            required: true
        },
        title: {
            type: String,
            required: true
        },
        progress: {
            type: Number,
            required: false,
            default: 0
        }
    },
    setup(props) {
        const imageURL = computed(() => `/assets/img/${props.image}`);
        const progressPercent = computed(() => `прогресс: ${props.progress}%`);

        return {
            imageURL,
            progressPercent
        };
    }
};
</script>

<style lang="scss" scoped>
@import '@/variables';

.training-card {
  position: relative;
  display: grid;
  grid-template-columns: 1fr 2fr;
  color: $primary-text-color;
  cursor: pointer;

  &:hover {
    box-shadow: 0 0 2px 2px $green-accent inset;
  }

  &__center {
    margin-left: 16px;
    font-size: 20px;
    font-weight: bold;
  }

  &__progress {
    position: absolute;
    bottom: 0;
    right: 0;
    font-size: 16px;
    padding: 12px;
  }
}

@media screen and (max-width: 650px) {
  .training-card {
    max-width: 350px;
    margin: 0 auto;
  }
}
</style>

// src/app/_components/training-card.tsx
import Image from "next/image";
import clsx from "clsx";

interface TrainingCardProps {
  title: string;
  image: string;
  progress?: number;
  className?: string;
  isBeta?: boolean;
}

export function TrainingCard({
  title,
  image,
  className,
  isBeta,
}: TrainingCardProps) {
  return (
    <div
      className={clsx(
        "relative mb-4 grid w-0 min-w-full cursor-pointer items-center rounded-[16px] bg-surface p-4 text-ink-2 shadow-[2px_3px_10px_rgba(0,0,0,0.2)] transition-shadow hover:shadow-[inset_0_0_2px_2px_#3eaf7c] max-[650px]:mx-auto max-[650px]:max-w-[350px]",
        className,
      )}
    >
      <div>
        <Image
          className="block h-auto max-w-full"
          src={`/card-icons/${image}`}
          alt={title}
          width={80}
          height={80}
        />
      </div>
      <div className="ml-4 text-[18px] font-bold leading-[24px]">{title}</div>
      {isBeta && (
        <div className="bg-ok absolute -right-3 -bottom-3 rounded-3xl px-5 py-2 text-sm font-semibold text-white max-[650px]:-right-2.5 max-[650px]:-bottom-2.5 max-[650px]:px-4 max-[650px]:py-1.5 max-[650px]:text-xs">
          бета-версия
        </div>
      )}
    </div>
  );
}
