// app/src/components/form/BaseRadioGroup.vue
<template>
  <div>
    <component
      v-for="option in options"
      :key="option"
      :is="(vertical) ? 'div' : 'span'"
      :class="{'horizontal': !vertical}"
    >
      <BaseRadio
        :value="option"
        :label="option"
        :name="name"
        :modelValue="modelValue"
        @update:modelValue="$emit('update:modelValue', $event)"
        :disabled="disabled"
        :isChosenCorrect="isChosenCorrect"
      />
    </component>
  </div>
</template>

<script>
import BaseRadio from '@/components/form/BaseRadio';

export default {
  name: 'BaseRadioGroup',
  components: {BaseRadio},
  props: {
    options: {
      type: Array,
      required: true
    },
    name: {
      type: String,
      required: true
    },
    modelValue: {
      type: [String, Number],
      required: true
    },
    vertical: {
      type: Boolean,
      default: false
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    isChosenCorrect: {
      type: Boolean,
      default: null,
    },
  }
};
</script>

<style scoped>
.horizontal {
  margin-right: 20px;
}
</style>

// src/app/_components/form/BaseRadioGroup.tsx
"use client";

import { BaseRadio } from "./BaseRadio";

type BaseRadioGroupProps = {
  options: (string | number)[];
  name: string;
  modelValue: string | number;
  onUpdate: (value: string | number) => void;
  vertical?: boolean;
  disabled?: boolean;
  isChosenCorrect?: boolean | null;
};

export const BaseRadioGroup = ({
  options,
  name,
  modelValue,
  onUpdate,
  vertical = false,
  disabled = false,
  isChosenCorrect = null,
}: BaseRadioGroupProps) => {
  return (
    <div>
      {options.map((option) => (
        <div key={option} className={vertical ? "block" : "mr-5 inline-block"}>
          <BaseRadio
            value={option}
            label={String(option)}
            name={name}
            modelValue={modelValue}
            onUpdate={onUpdate}
            disabled={disabled}
            isChosenCorrect={isChosenCorrect}
          />
        </div>
      ))}
    </div>
  );
};
