// app/src/components/form/BaseInput.vue
<template>
    <div class="form-control">
        <label :for=id>{{ label }}</label>
        <input
                v-bind=$attrs
                :id=id
                :placeholder="placeholder"
                :value="modelValue"
                @input="$emit('update:modelValue', $event.target.value)"
        >
    </div>
</template>

<script>
export default {
    name: 'BaseInput',
    props: {
        label: {
            type: String,
            required: true,
            default: ''
        },
        placeholder: {
            type: String,
            required: false,
            default: (props) => props.label,
        },
        modelValue: {
            type: [String, Number],
            default: ''
        }
    },
    setup() {
        const id = `base-input-${Math.random()}`;
        return {id};
    }
};
</script>

<style scoped>

</style>

// src/app/_components/form/BaseInput.tsx
"use client";

import { type InputHTMLAttributes } from "react";
import styles from "./form.module.css";

type BaseInputProps = InputHTMLAttributes<HTMLInputElement> & {
  modelValue: string | number;
  onUpdate: (value: string) => void;
  label?: string;
};

export const BaseInput = ({
  modelValue,
  onUpdate,
  label,
  ...props
}: BaseInputProps) => {
  const id = `base-input-${Math.random()}`;

  return (
    <div className={styles.formControl}>
      {label && <label htmlFor={id}>{label}</label>}
      <input
        {...props}
        id={id}
        value={modelValue}
        onChange={(e) => onUpdate(e.target.value)}
        className={`${styles.formInput} ${props.className ?? ""}`}
      />
    </div>
  );
};
