// app/src/views/UseOfEnglish.vue
<template>
    <main>
        <AppTrainingPage :topic="topic" ref="page" @check-answers="checkAnswers">
            <template #training-instruction>
                <p>
                    Преобразуйте слова, напечатанные заглавными буквами так, чтобы они грамматически и лексически
                    соответствовали содержанию текстов.
                </p>
                <p>
                    Заполните пропуски полученными словами.
                </p>
                <p>
                    Слова вводите заглавными буквами, без пробелов, как в экзаменационном бланке.
                </p>
                <p>
                    Глагольные формы вводите без сокращений.
                </p>
            </template>

            <template #training-content>
                <UseOfEnglishCard
                        v-for="(question, i) in questions"
                        :key="question._id"
                        :id="question._id"
                        :question="question.task"
                        :origin="question.origin"
                        :ref="el => { if (el) uoeCards[i] = el }"
                />
            </template>
        </AppTrainingPage>
    </main>
</template>

<script>
import UseOfEnglishCard from '@/components/cards/UseOfEnglishCard';
import {computed, onBeforeUpdate, onMounted, ref} from 'vue';
import {API} from '@/services/api';
import {replaceCharSequence} from '@/utils/replaceCharSequence';
import AppTrainingPage from '@/components/AppTrainingPage';

export default {
    name: 'UseOfEnglish',
    components: {AppTrainingPage, UseOfEnglishCard},
    props: {
        topic: {
            type: String
        }
    },
    setup(props) {
        const page = ref(null);
        const questions = ref([]);
        const uoeCards = ref([]);

        onMounted(async () => {
            API.getUoeTraining(props.topic)
                .then((res) => {
                    questions.value = res.data.questions;
                    page.value.setShowInstruction(true);
                })
                .catch((err) => console.log(err));
        });

        onBeforeUpdate(() => uoeCards.value = []);

        const rightAnswersNumber = ref(null);
        const result = computed(() => {
            const resultRatio = (rightAnswersNumber.value === null || questions.value === null) ? null :
                `${rightAnswersNumber.value}/${questions.value.length}`;
            return `Ваш результат: ${resultRatio}`;
        });

        const checkAnswers = async () => {
            page.value.setIsChecking(true);

            const userAnswers = uoeCards.value.map((cardComponent) => cardComponent.getAnswerData());
            const checkResultResponse = await API.checkTraining('use-of-english', userAnswers);
            const rightAnswers = checkResultResponse.data.rightAnswers;
            rightAnswersNumber.value = checkResultResponse.data.result;

            uoeCards.value.forEach((cardComponent, index) => {
                const givenAnswer = userAnswers[index].answer;
                const rightAnswer = rightAnswers.find((el) => el._id === userAnswers[index]._id).rightAnswer;
                cardComponent.setIsCorrect(givenAnswer === rightAnswer);
                const relevantQuestion = questions.value.find((question) => question._id === userAnswers[index]._id);
                relevantQuestion.task = replaceCharSequence(relevantQuestion.task, '_',
                    rightAnswer, {tagWrapper: 'strong'});
            });

            page.value.setResult(result.value);
        };

        return {
            page,
            questions,
            uoeCards,
            result,
            checkAnswers
        };
    }
};
</script>

<style lang="scss" scoped>
@import '@/variables';

main {
  flex-grow: 1;
  margin: 32px auto;
}
</style>

// oge-eng-web/src/app/training/use-of-english/page.tsx
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { api } from "@/trpc/react";
import { TrainingPage } from "@/app/_components/TrainingPage";
import {
  UseOfEnglishCard,
  type UseOfEnglishCardRef,
} from "@/app/_components/UseOfEnglishCard";
import styles from "@/app/_components/TrainingPage.module.css";

export default function UseOfEnglishPage() {
  const searchParams = useSearchParams();
  const topicId = Number(searchParams.get("topic"));

  const cardRefs = useRef<UseOfEnglishCardRef[]>([]);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const { data, isLoading } = api.training.getUoeTraining.useQuery(
    { topicId },
    {
      enabled: !!topicId,
      refetchOnWindowFocus: false,
      gcTime: 0,
    },
  );

  const checkAnswersMutation = api.training.checkUoeTraining.useMutation();

  const [isChecking, setIsChecking] = useState(false);
  const [isChecked, setIsChecked] = useState(false);
  const [resultText, setResultText] = useState("");

  const handleCheck = async () => {
    setIsChecking(true);
    const answers = cardRefs.current.map((ref) => ref.getAnswerData());
    const result = await checkAnswersMutation.mutateAsync({ answers });

    result.results.forEach((res) => {
      const cardRef = cardRefs.current.find(
        (ref) => ref.getAnswerData().id === res.id,
      );
      cardRef?.setIsCorrect(res.isCorrect);
      if (!res.isCorrect) {
        const task = data?.tasks.find((t) => t.id === res.id);
        if (task) {
          cardRef?.setQuestion(
            task.task.replace(
              "_".repeat(18),
              `<strong>${res.correctAnswer}</strong>`,
            ),
          );
        }
      }
    });

    setResultText(`Ваш результат: ${result.correctCount}/${result.total}`);
    setIsChecking(false);
    setIsChecked(true);
  };

  const instruction = useMemo(
    () => (
      <>
        <p>
          Преобразуйте слова, напечатанные заглавными буквами так, чтобы они
          грамматически и лексически соответствовали содержанию текстов.
        </p>
        <p>Заполните пропуски полученными словами.</p>
        <p>
          Слова вводите заглавными буквами, без пробелов, как в экзаменационном
          бланке.
        </p>
        <p>Глагольные формы вводите без сокращений.</p>
      </>
    ),
    [],
  );

  if (!isLoading && !data) {
    return <div>Не удалось загрузить задание. Попробуйте еще раз.</div>;
  } else if (!data) {
    return <></>;
  }

  return (
    <main className={styles.trainingPage}>
      <TrainingPage
        topic={data.topicTitle}
        instruction={instruction}
        onCheck={handleCheck}
        isChecking={isChecking}
        isChecked={isChecked}
        resultText={resultText}
      >
        {data.tasks.map((task, i) => (
          <UseOfEnglishCard
            key={task.id}
            ref={(el) => {
              if (el) cardRefs.current[i] = el;
            }}
            id={task.id}
            question={task.task}
            origin={task.origin}
          />
        ))}
      </TrainingPage>
    </main>
  );
}
